### ISSUE TITLE
license

### ISSUE THREAD

**Issue by nickdesaulniers** [linux-3ds/arm9linuxfw#1]
what license was this code original written under? cc @xerpi

**Comment by Wolfvak** [comment]
now that I think about it I'm not sure, the only requirement is that it needs to be mpl or gpl2 compatible because of sdmmc, which has been rewritten and will be pushed out in a few days anyway.

I guess gpl2 sounds about right for this kind of thing, I'll add the license asap

**Comment by nickdesaulniers** [comment]
GPLv2 SGTM; it would be good to have explicit confirmation from @xerpi though. I wouldn't add it until then.

In particular having a "yes, you can send this code upstream with my name on it" would be most reassuring for the kernel.  I'm happy to try to maintain proper authorship on the commits when breaking things up into individual patches.

We can just put the text in a top level LICENSE.txt or .md file. For the kernel, we'll need https://github.com/linux-3ds/linux/issues/3.

**Comment by xerpi** [comment]
I actually didn't put any license originally... but yeah GPLv2 sounds good!
And yes, you can send any code related to this: FIRM loader, arm9linuxfw, Linux kernel, upstream with my name on it!
Also, feel free to remove my email (actually, let's do it) `<xerpi.g.12@gmail.com>`  from the few places in the linux repo where I added this (let's just keep my name, no email).

**Comment by nickdesaulniers** [comment]
sure, I'll send cleanups for that.  When we send kernel patches upstream, we can stage a branch with broken out commits.  We should try hard to retain the original author in git, with subsequent authors credited in the commit message (is the kernel convention).  At that point I'll need to apply your signed off by tag, which means you agree to: https://www.kernel.org/doc/html/v4.17/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin.  But we should file a seperate issue to discuss upstreaming kernel patches once things are working well for a few folks.
