### ISSUE TITLE
How is the write support progress going?

### ISSUE THREAD

**Issue by iAmInActions** [linux-3ds/arm9linuxfw#21]
Hi, I was wondering if there were any new steps towards working write support besides c14469d16d5a6a6eebc347525df2bce9ac9ec86b. I'm just asking bc I haven't seen any public progress to this repository in the last weeks. If you guys need to take your time, that's totally fine. I just wanted to ask.

**Comment by Wolfvak** [comment]
im actually ditching the whole arm9linuxfw in favor of a simpler approach, it can do read/write ops to sd at around 4MiB/s right now with PIO running in 16bit mode, I'm working on getting 32bit + DMA working

**Comment by iAmInActions** [comment]
> im actually ditching the whole arm9linuxfw in favor of a simpler approach, it can do read/write ops to sd at around 4MiB/s right now with PIO running in 16bit mode, I'm working on getting 32bit + DMA working

Any way i could try it?
