### ISSUE TITLE
move triple to arm-linux-gnueabi

### ISSUE THREAD

**Issue by nickdesaulniers** [linux-3ds/arm9linuxfw#4]
I know that technically we're not targeting a hosted environment, but:
1. that's the triple the kernel uses (arm-linux-gnueabihf is also supported, but arm11 has VFP which isn't? hard FP. oabi is also supported by the kernel but kind of superseded by eabi).
2. it's a huge dependency:
```sh
$  sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi
...
The following additional packages will be installed:
  libnewlib-arm-none-eabi libnewlib-dev libstdc++-arm-none-eabi-newlib
Suggested packages:
  libnewlib-doc
The following NEW packages will be installed:
  binutils-arm-none-eabi gcc-arm-none-eabi libnewlib-arm-none-eabi libnewlib-dev libstdc++-arm-none-eabi-newlib
0 upgraded, 5 newly installed, 0 to remove and 4 not upgraded.
Need to get 271 MB of archives.
After this operation, 2,340 MB of additional disk space will be used.
```
woof.  Since we're using arm-linux-gnuabi for the kernel which is the largest project, it would be nice to standardize all projects on that, if possible.

**Comment by nickdesaulniers** [comment]
I suspect libnewlib-arm-none-eabi will still be needed, but I think we should be able to use `arm-linux-gnueabi-gcc` and tell it to use newlib rather than glibc.

**Comment by Wolfvak** [comment]
this is meant to be compiled with devkitARM, but we can move to a more standard target

**Comment by nickdesaulniers** [comment]
I was able to build successfully with arm-none-eabi-gcc: https://github.com/linux-3ds/arm9linuxfw/wiki#how-to-build

From what I can tell that's what devkitARM is using. Both are configured to use newlib, IIUC.

**Comment by nickdesaulniers** [comment]
Since I have the bootloader building now with arm-none-eabi, I think I'm happy to just close this out. As long as I don't have to use devkitARM.
